### PR TITLE
Improve website look

### PR DESCRIPTION
**Pull request by olivroy**
I would recommend adding it to the About section on the gh homepage:

image

Also, if you want the website to update automatically, you can run `usethis::use_pkgdown_github_pages()` locally. (I can't do it since I do not have write access). 

Here is the new look: 

image

### CODE REVIEW

**Comment by smouksassi** [comment]
thanks !

**Comment by smouksassi** [comment]
which rlang version are you using ? latest on CRAN ?

**Comment by olivroy** [comment]
Latest, did you notice an issue?

**Comment by smouksassi** [comment]
LGTM already merged

**Pull request merged**
